import type { InsuranceProduct, Provider } from './types';

export const mockProviders: Provider[] = [
  { id: 'provider-1', name: 'GreenLeaf Insurance', logoUrl: 'https://placehold.co/40x40/228B22/FFFFFF' },
  { id: 'provider-2', name: 'StableTrust Assurance', logoUrl: 'https://placehold.co/40x40/808080/FFFFFF' },
  { id: 'provider-3', name: 'Growth Mutual', logoUrl: 'https://placehold.co/40x40/000000/FFFFFF' },
];

export const mockInsuranceProducts: InsuranceProduct[] = [
  {
    id: 'prod-1',
    providerId: 'provider-1',
    name: 'Vitality Health Plan',
    type: 'health',
    description: 'Comprehensive health coverage for you and your family, ensuring peace of mind.',
    price: 350,
    coverage: ['Hospitalization', 'Outpatient Care', 'Prescription Drugs'],
    providerName: 'GreenLeaf Insurance',
    providerLogoUrl: 'https://placehold.co/40x40/228B22/FFFFFF',
  },
  {
    id: 'prod-2',
    providerId: 'provider-2',
    name: 'AutoGuard Secure',
    type: 'auto',
    description: 'Protect your vehicle against accidents, theft, and damages with our top-tier auto insurance.',
    price: 120,
    coverage: ['Collision', 'Theft', 'Liability'],
    providerName: 'StableTrust Assurance',
    providerLogoUrl: 'https://placehold.co/40x40/808080/FFFFFF',
  },
  {
    id: 'prod-3',
    providerId: 'provider-3',
    name: 'LifeLegacy Plus',
    type: 'life',
    description: 'Secure your family\'s future with a flexible and robust life insurance policy.',
    price: 80,
    coverage: ['Financial Security', 'Legacy Planning', 'Funeral Expenses'],
    providerName: 'Growth Mutual',
    providerLogoUrl: 'https://placehold.co/40x40/000000/FFFFFF',
  },
  {
    id: 'prod-4',
    providerId: 'provider-1',
    name: 'Wellness Pro Health',
    type: 'health',
    description: 'A premium health plan focusing on preventive care and wellness programs.',
    price: 450,
    coverage: ['Full Medical', 'Wellness Programs', 'Dental & Vision'],
    providerName: 'GreenLeaf Insurance',
    providerLogoUrl: 'https://placehold.co/40x40/228B22/FFFFFF',
  },
  {
    id: 'prod-5',
    providerId: 'provider-2',
    name: 'RoadMaster Auto',
    type: 'auto',
    description: 'Complete auto coverage with roadside assistance and rental car reimbursement.',
    price: 150,
    coverage: ['Full Coverage', 'Roadside Assistance', 'Rental Reimbursement'],
    providerName: 'StableTrust Assurance',
    providerLogoUrl: 'https://placehold.co/40x40/808080/FFFFFF',
  },
  {
    id: 'prod-6',
    providerId: 'provider-3',
    name: 'Evergreen Life',
    type: 'life',
    description: 'A whole life insurance policy that builds cash value over time.',
    price: 200,
    coverage: ['Permanent Coverage', 'Cash Value Growth', 'Tax Benefits'],
    providerName: 'Growth Mutual',
    providerLogoUrl: 'https://placehold.co/40x40/000000/FFFFFF',
  },
];
